version: '3.8'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: myapp_db
    ports:
      - "5432:5432"
  
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
  
  redis: